(function(){
'use strict';
var SUPA_URL='https://ngidsolvxegpyrprlbex.supabase.co';
var SUPA_KEY='sb_publishable_-8u67PtkHJj1yRVWtOIkog_2skdsDcz';
var MODES={geral:'Assistente geral',idiomas:'Professor de idiomas',juridico:'Assistente jurídico',saude:'Saúde e bem-estar',empresa:'Assistente empresarial'};
var mode='geral', history=[];
function client(){if(window.__ilAiClient)return window.__ilAiClient;if(!window.supabase||!window.supabase.createClient)return null;window.__ilAiClient=window.supabase.createClient(SUPA_URL,SUPA_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});return window.__ilAiClient}
function add(box,text,who){var d=document.createElement('div');d.className='ilai-msg '+(who==='user'?'ilai-user':'ilai-ai');d.textContent=text;box.appendChild(d);box.scrollTop=box.scrollHeight}
function build(){if(document.querySelector('.ilai-btn'))return;var b=document.createElement('button');b.type='button';b.className='ilai-btn';b.title='Abrir IL IA';b.setAttribute('aria-label','Abrir IL IA');document.body.appendChild(b);var p=document.createElement('section');p.className='ilai-panel';p.setAttribute('aria-label','IL IA');p.innerHTML='<div class="ilai-head"><img class="ilai-lion" src="./logo-chats.png" alt=""><div class="ilai-title"><b>🦁 IL IA</b><small>Seu assistente dentro do IL Chats</small></div><button class="ilai-close" type="button">×</button></div><div class="ilai-modes"></div><div class="ilai-msgs"></div><div class="ilai-note">IA pode cometer erros. Em saúde, direito e outras áreas profissionais, use como apoio e confirme decisões importantes com profissional habilitado.</div><form class="ilai-form"><input class="ilai-input" autocomplete="off" placeholder="Converse com a IL IA…"><button class="ilai-send" type="submit">Enviar</button></form>';document.body.appendChild(p);
var modes=p.querySelector('.ilai-modes');Object.keys(MODES).forEach(function(k){var x=document.createElement('button');x.type='button';x.className='ilai-mode'+(k===mode?' active':'');x.dataset.mode=k;x.textContent=MODES[k];x.onclick=function(){mode=k;modes.querySelectorAll('.ilai-mode').forEach(function(y){y.classList.toggle('active',y.dataset.mode===k)});add(p.querySelector('.ilai-msgs'),'Modo alterado para '+MODES[k]+'. Como posso ajudar?','ai')};modes.appendChild(x)});
var msgs=p.querySelector('.ilai-msgs');add(msgs,'Olá! Eu sou a IL IA 🦁. Posso conversar, ajudar nos estudos, praticar idiomas e auxiliar em tarefas profissionais.','ai');b.onclick=function(){p.classList.toggle('open')};p.querySelector('.ilai-close').onclick=function(){p.classList.remove('open')};p.querySelector('.ilai-form').onsubmit=async function(e){e.preventDefault();var input=p.querySelector('.ilai-input'),send=p.querySelector('.ilai-send'),text=input.value.trim();if(!text)return;input.value='';add(msgs,text,'user');history.push({role:'user',content:text});send.disabled=true;try{var c=client();if(!c)throw new Error('Supabase indisponível');var sess=await c.auth.getSession();if(!sess.data||!sess.data.session){throw new Error('Entre na sua conta do IL Chats para usar a IL IA.')};var r=await c.functions.invoke('il-ai',{body:{message:text,mode:mode,history:history.slice(-10)}});if(r.error)throw r.error;var answer=r.data&&r.data.answer;if(!answer)throw new Error('A IA não retornou uma resposta.');history.push({role:'assistant',content:answer});add(msgs,answer,'ai')}catch(err){add(msgs,'Ainda não consegui conectar à IL IA. '+(err&&err.message?err.message:'Verifique a configuração do servidor.'),'ai')}finally{send.disabled=false;input.focus()}}}
function install(){if(document.querySelector('.auth-card'))return;build()}
new MutationObserver(install).observe(document.documentElement,{childList:true,subtree:true});install();
})();
