(()=>{const $=s=>document.querySelector(s),input=$("#miokoV33Input"),send=$("#miokoV33Send"),cap=$("#mv30Caption"),avatar=$("#mv30Avatar"),ptBox=$("#miokoV34Explain"),pt=$("#miokoV34Pt");let history=[];
async function tts(japanese){
 if(!japanese)return;
 try{const {data,error}=await window.supabaseClient.functions.invoke("il-tts",{body:{text:japanese,language:"ja"}});if(error)throw error;const b=data?.audio_base64||data?.audio;if(!b)throw Error("Áudio não retornado");const a=new Audio("data:"+(data?.mime_type||"audio/mpeg")+";base64,"+b);
  let ctx,src,analyser,raf; const mouth=()=>{avatar?.classList.add("speaking");try{ctx=new (window.AudioContext||window.webkitAudioContext)();src=ctx.createMediaElementSource(a);analyser=ctx.createAnalyser();analyser.fftSize=256;src.connect(analyser);analyser.connect(ctx.destination);const arr=new Uint8Array(analyser.frequencyBinCount);const tick=()=>{analyser.getByteFrequencyData(arr);let sum=0;for(let i=0;i<arr.length;i++)sum+=arr[i];const level=sum/arr.length;avatar?.style.setProperty("--mioko-mouth",Math.min(1,level/55).toFixed(2));raf=requestAnimationFrame(tick)};tick()}catch(_){}};
  mouth();const stop=()=>{avatar?.classList.remove("speaking");avatar?.style.removeProperty("--mioko-mouth");if(raf)cancelAnimationFrame(raf);if(ctx)ctx.close().catch(()=>{})};a.onended=stop;a.onerror=stop;await a.play()}catch(e){avatar?.classList.remove("speaking");console.error(e)}
}
async function ask(){const msg=input?.value.trim();if(!msg)return;input.value="";send.disabled=true;cap.textContent="みおこ先生は考えています…";ptBox.hidden=true;try{if(!window.supabaseClient?.functions)throw Error("Supabase não inicializado");history.push({role:"user",content:msg});const {data,error}=await window.supabaseClient.functions.invoke("il-ai",{body:{message:msg,history:history.slice(-18),language:"ja",mode:"open_conversation_v38",first_contact:history.length<=1}});if(error)throw error;const ja=data?.japanese||"", explanation=data?.portuguese||"";if(!ja)throw Error(data?.error||"Resposta japonesa vazia");history.push({role:"assistant",content:ja+(explanation?`\n[PT] ${explanation}`:"")});cap.textContent=ja;if(explanation){pt.textContent=explanation;ptBox.hidden=false}await tts(ja)}catch(e){cap.textContent="Erro ao falar com a Mioko: "+(e?.message||e)}finally{send.disabled=false;input?.focus()}}
send?.addEventListener("click",ask);input?.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();ask()}});
})();
